apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports_analytics
  namespace: staging
spec:
  replicas: 1   
  selector:
    matchLabels:
      app: reports_analytics
  template:
    metadata:
      labels:
        app: reports_analytics
    spec:
      containers:
      - name: reports_analytics
        image: 024955634588.dkr.ecr.eu-north-1.amazonaws.com/reports_analytics:latest
        ports:
        - containerPort: 8006
