apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment_service
  namespace: staging
spec:
  replicas: 0   # <---- IMPORTANT FOR NOW
  selector:
    matchLabels:
      app: appointment_service
  template:
    metadata:
      labels:
        app: appointment_service
    spec:
      containers:
      - name: appointment_service
        image: <ECR_URL>/appointment_service:latest
        ports:
        - containerPort: 8004
