apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment_service
  namespace: staging
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: appointment_service
  template:
    metadata:
      labels:
        app: appointment_service
    spec:
      containers:
      - name: appointment_service
        image: 024955634588.dkr.ecr.eu-north-1.amazonaws.com/appointment_service:latest
        ports:
        - containerPort: 8004
