apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-salon-routes
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/WSO2-G02/salon-gitops.git
    targetRevision: HEAD
    path: production
    directory:
      include: 'salon-routes.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
