apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
    version: "v1.89.0"
data:
  config.yaml: |
    external_services:
      prometheus:
        url: "http://prometheus-kube-prometheus-prometheus.monitoring:9090"
